baseURL = "https:/www.vanhuyz.com"
disablePathToLower = true
languageCode = "en-us"
title = "vanhuyz's notes"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"
googleAnalytics = "G-PEBPY7GKR4"
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "vanhuyz's blogs"
  facebook = "https://www.facebook.com/vanhuyz"
  twitter = "https://twitter.com/vanhuyz"
  instagram = ""
  youtube = ""
  github = "https://github.com/vanhuyz"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/vanhuyz/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/fuji.jpg"
  recent_posts_number = 10
  body_classes = "helvetica bg-near-white"
  post_content_classes = "helvetica"
