baseURL = "https://vanhuyz.github.io/"
disablePathToLower = true
languageCode = "en-us"
title = "vanhuyz's notes"
theme = "gohugo-theme-ananke"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
